version: '3.8'
services:
  app:
    image: node:20
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: talkroom
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "4242:4242"
    networks:
      - server-network
    command: npm start
networks:
  server-network:
    external: true